feat: rename user to participant
SuperViz/sdk pull request #194
Opened 2023-02-06 22:08 UTC by brunokunace

2023-02-06 23:01 UTC, carlossantos74 requested changes

2023-02-07 11:41 UTC, carlossantos74 approved these changes

2023-02-07 11:41 UTC, carlossantos74 commented on src/services/integration/index.ts
>  import { AblyRealtimeData } from '../realtime/ably/types';
```suggestion
import { AblyRealtimeData, AblyParticipant } from '../realtime/ably/types';
```

2023-02-07 11:43 UTC, carlossantos74 commented on src/services/integration/index.ts
>  import { AblyRealtimeData } from '../realtime/ably/types';
You should import `AblyParticipant` to use as type

2023-02-07 11:58 UTC, afonsovinicius approved these changes

2023-02-07 14:15 UTC, merged