feat: add meeting kick user
SuperViz/sdk pull request #275
Opened 2023-07-26 12:06 UTC by afonsovinicius

2023-07-26 12:46 UTC, vitorvargasdev approved these changes

2023-07-26 12:51 UTC, carlossantos74 requested changes

2023-07-26 12:51 UTC, carlossantos74 commented on src/common/types/events.types.ts
> +  REALTIME_KICK_PARTICIPANT = 'realtime.kick-participant',
```suggestion
```

2023-07-27 10:04 UTC, carlossantos74 approved these changes

2023-07-27 10:04 UTC, merged