feat: annotation pin
SuperViz/sdk pull request #338
Opened 2023-09-25 14:41 UTC by carlossantos74

2023-09-25 14:45 UTC, SuperViz-Dev commented
Total Coverage: <b>93.10%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/shims.d.ts'>shims.d.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common</b></td></tr><tr><td colspan='5'><b>src/common/types</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/common/types/events.types.ts'>events.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/common/types/meeting-colors.types.ts'>meeting-colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/common/types/participant.types.ts'>participant.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/common/types/realtime.types.ts'>realtime.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/common/types/sdk-options.types.ts'>sdk-options.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common/utils</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/common/utils/do-request.ts'>do-request.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/common/utils/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/common/utils/logger.ts'>logger.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/common/utils/observer.ts'>observer.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/common/utils/sleep.ts'>sleep.ts</a></td>
<td><b>0%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/common/utils/sleep.ts#L2>2</a></td></tr><tr><td colspan='5'><b>src/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><b>66.67%</b></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/components/comments/index.ts'>index.ts</a></td>
<td><b>83.33%</b></td>
<td><b>92.31%</b></td>
<td><b>96.26%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/components/comments/index.ts#L300>300</a>, <a href=https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/components/comments/index.ts#L300>300</a>, <a href=https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/components/comments/index.ts#L301>301</a>, <a href=https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/components/comments/index.ts#L304>304</a>, <a href=https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/components/comments/index.ts#L81>81</a></td></tr><tr><td colspan='5'><b>src/components/presence-mouse</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/components/presence-mouse/index.ts'>index.ts</a></td>
<td><b>73.91%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/components/presence-mouse/index.ts#L132>132</a>, <a href=https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/components/presence-mouse/index.ts#L83>83</a>, <a href=https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/components/presence-mouse/index.ts#L90>90</a>, <a href=https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/components/presence-mouse/index.ts#L91>91</a>, <a href=https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/components/presence-mouse/index.ts#L92>92</a>, <a href=https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/components/presence-mouse/index.ts#L93>93</a></td></tr><tr><td colspan='5'><b>src/components/video</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/components/video/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/core</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/core/index.ts'>index.ts</a></td>
<td><b>88.89%</b></td>
<td><span>100%</span></td>
<td><b>87.50%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/core/index.ts#L49>49</a>, <a href=https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/core/index.ts#L50>50</a>, <a href=https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/core/index.ts#L67>67</a>, <a href=https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/core/index.ts#L71>71</a>, <a href=https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/core/index.ts#L73>73</a>, <a href=https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/core/index.ts#L83>83</a></td></tr><tr><td colspan='5'><b>src/core/launcher</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/core/launcher/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/services</b></td></tr><tr><td colspan='5'><b>src/services/api</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/services/api/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><b>92.31%</b></td>
<td><b>93.18%</b></td>
<td><a href=https://github.co [...]

2023-09-25 14:45 UTC, SuperViz-Dev commented
Total Coverage: <b>99.83%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td colspan='5'><b>src/web-components</b></td></tr><tr><td colspan='5'><b>src/web-components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/base/styles</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/base/styles/icon-button.style.ts'>icon-button.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/base/styles/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/base/styles/sv-hr.style.ts'>sv-hr.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/base/styles/typography.style.ts'>typography.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/base/styles/variables.style.ts'>variables.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/comments/comments.ts'>comments.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/comments/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/comments/components/annotation-filter.ts'>annotation-filter.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/comments/components/annotation-item.ts'>annotation-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/comments/components/annotation-pin.ts'>annotation-pin.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/comments/components/annotation-resolved.ts'>annotation-resolved.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/comments/components/annotations.ts'>annotations.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/comments/components/comment-input.ts'>comment-input.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/comments/components/comment-item.ts'>comment-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/comments/components/content.ts'>content.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/comments/components/delete-comment-modal.ts'>delete-comment-modal.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/comments/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/comments/components/topbar.ts'>topbar.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/comments/components/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/css</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/comments/css/annotation-filter.style.ts'>annotation-filter.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/comments/css/annotation-item.style.ts'>annotation-item.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/comments/css/annotation-pin.style.ts'>annotation-pin.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/comments/css/annotation-resolved.style.ts'>annotation-resolved.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/comments/css/annotations.style.ts'>annotations.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/39b8ed2c7b9f702511e3c1a6ef260aba015e84c2/src/web-components/comments/css/comment-input.style.ts'>comment-input.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href= [...]

2023-09-26 10:49 UTC, SuperViz-Dev commented
Total Coverage: <b>99.83%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td colspan='5'><b>src/web-components</b></td></tr><tr><td colspan='5'><b>src/web-components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/base/styles</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/base/styles/icon-button.style.ts'>icon-button.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/base/styles/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/base/styles/sv-hr.style.ts'>sv-hr.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/base/styles/typography.style.ts'>typography.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/base/styles/variables.style.ts'>variables.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/comments/comments.ts'>comments.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/comments/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/comments/components/annotation-filter.ts'>annotation-filter.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/comments/components/annotation-item.ts'>annotation-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/comments/components/annotation-pin.ts'>annotation-pin.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/comments/components/annotation-resolved.ts'>annotation-resolved.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/comments/components/annotations.ts'>annotations.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/comments/components/comment-input.ts'>comment-input.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/comments/components/comment-item.ts'>comment-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/comments/components/content.ts'>content.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/comments/components/delete-comment-modal.ts'>delete-comment-modal.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/comments/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/comments/components/topbar.ts'>topbar.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/comments/components/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/css</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/comments/css/annotation-filter.style.ts'>annotation-filter.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/comments/css/annotation-item.style.ts'>annotation-item.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/comments/css/annotation-pin.style.ts'>annotation-pin.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/comments/css/annotation-resolved.style.ts'>annotation-resolved.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/comments/css/annotations.style.ts'>annotations.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/fd5fb78771577c15394d8b12752516ee0d85d213/src/web-components/comments/css/comment-input.style.ts'>comment-input.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href= [...]

2023-09-26 11:04 UTC, SuperViz-Dev commented
Total Coverage: <b>99.83%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td colspan='5'><b>src/web-components</b></td></tr><tr><td colspan='5'><b>src/web-components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/base/styles</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/base/styles/icon-button.style.ts'>icon-button.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/base/styles/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/base/styles/sv-hr.style.ts'>sv-hr.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/base/styles/typography.style.ts'>typography.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/base/styles/variables.style.ts'>variables.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/comments/comments.ts'>comments.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/comments/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/comments/components/annotation-filter.ts'>annotation-filter.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/comments/components/annotation-item.ts'>annotation-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/comments/components/annotation-pin.ts'>annotation-pin.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/comments/components/annotation-resolved.ts'>annotation-resolved.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/comments/components/annotations.ts'>annotations.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/comments/components/comment-input.ts'>comment-input.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/comments/components/comment-item.ts'>comment-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/comments/components/content.ts'>content.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/comments/components/delete-comment-modal.ts'>delete-comment-modal.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/comments/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/comments/components/topbar.ts'>topbar.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/comments/components/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/css</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/comments/css/annotation-filter.style.ts'>annotation-filter.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/comments/css/annotation-item.style.ts'>annotation-item.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/comments/css/annotation-pin.style.ts'>annotation-pin.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/comments/css/annotation-resolved.style.ts'>annotation-resolved.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/comments/css/annotations.style.ts'>annotations.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/07341f5a9399b5630e6e20c0fc49d4692f2d4423/src/web-components/comments/css/comment-input.style.ts'>comment-input.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href= [...]

2023-09-27 11:33 UTC, SuperViz-Dev commented
Total Coverage: <b>92.66%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/shims.d.ts'>shims.d.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common</b></td></tr><tr><td colspan='5'><b>src/common/types</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/common/types/events.types.ts'>events.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/common/types/meeting-colors.types.ts'>meeting-colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/common/types/participant.types.ts'>participant.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/common/types/realtime.types.ts'>realtime.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/common/types/sdk-options.types.ts'>sdk-options.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common/utils</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/common/utils/do-request.ts'>do-request.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/common/utils/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/common/utils/logger.ts'>logger.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/common/utils/observer.ts'>observer.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/common/utils/sleep.ts'>sleep.ts</a></td>
<td><b>0%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/common/utils/sleep.ts#L2>2</a></td></tr><tr><td colspan='5'><b>src/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><b>50%</b></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/components/comments/index.ts'>index.ts</a></td>
<td><b>83.33%</b></td>
<td><b>88.89%</b></td>
<td><b>95.45%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/components/comments/index.ts#L316>316</a>, <a href=https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/components/comments/index.ts#L316>316</a>, <a href=https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/components/comments/index.ts#L317>317</a>, <a href=https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/components/comments/index.ts#L320>320</a>, <a href=https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/components/comments/index.ts#L77>77</a>, <a href=https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/components/comments/index.ts#L97>97</a></td></tr><tr><td colspan='5'><b>src/components/comments/canvas-pin-adapter</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/components/comments/canvas-pin-adapter/index.ts'>index.ts</a></td>
<td><b>50%</b></td>
<td><span>100%</span></td>
<td><b>97.96%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/components/comments/canvas-pin-adapter/index.ts#L110>110</a>, <a href=https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/components/comments/canvas-pin-adapter/index.ts#L111>111</a>, <a href=https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/components/comments/canvas-pin-adapter/index.ts#L141>141</a></td></tr><tr><td colspan='5'><b>src/components/presence-mouse</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/components/presence-mouse/index.ts'>index.ts</a></td>
<td><b>73.91%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/components/presence-mouse/index.ts#L132>132</a>, <a href=https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/components/presence-mouse/index.ts#L83>83</a>, <a href=https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/components/presence-mouse/index.ts#L90>90</a>, <a href=https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/components/presence-mouse/index.ts#L91>91</a>, <a href=https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/components/presence-mouse/index.ts#L92>92</a>, <a href=https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/components/presence-mouse/index.ts#L93>93</a></td></tr><tr><td colspan='5'><b>src/components/video</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/components/video/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/core</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/core/index.ts'>index.ts</a></td>
<td><b>88.89%</b></td>
<td><span>100%</span></td>
<td><b>87.50%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/core/index.ts#L49>49</a>, <a href=https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/core/index.ts#L50>50</a>, <a href=https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/core/index.ts#L67>67</a>, <a href=https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/co [...]

2023-09-27 11:33 UTC, SuperViz-Dev commented
Total Coverage: <b>99.83%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td colspan='5'><b>src/web-components</b></td></tr><tr><td colspan='5'><b>src/web-components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/base/styles</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/base/styles/icon-button.style.ts'>icon-button.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/base/styles/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/base/styles/sv-hr.style.ts'>sv-hr.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/base/styles/typography.style.ts'>typography.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/base/styles/variables.style.ts'>variables.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/comments/comments.ts'>comments.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/comments/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/comments/components/annotation-filter.ts'>annotation-filter.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/comments/components/annotation-item.ts'>annotation-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/comments/components/annotation-pin.ts'>annotation-pin.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/comments/components/annotation-resolved.ts'>annotation-resolved.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/comments/components/annotations.ts'>annotations.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/comments/components/comment-input.ts'>comment-input.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/comments/components/comment-item.ts'>comment-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/comments/components/content.ts'>content.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/comments/components/delete-comment-modal.ts'>delete-comment-modal.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/comments/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/comments/components/topbar.ts'>topbar.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/comments/components/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/css</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/comments/css/annotation-filter.style.ts'>annotation-filter.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/comments/css/annotation-item.style.ts'>annotation-item.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/comments/css/annotation-pin.style.ts'>annotation-pin.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/comments/css/annotation-resolved.style.ts'>annotation-resolved.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/comments/css/annotations.style.ts'>annotations.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/c6d4e257a64647461f58adb595bb12ef9e59b27c/src/web-components/comments/css/comment-input.style.ts'>comment-input.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href= [...]

2023-09-27 23:13 UTC, SuperViz-Dev commented
Total Coverage: <b>92.69%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/shims.d.ts'>shims.d.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common</b></td></tr><tr><td colspan='5'><b>src/common/types</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/common/types/events.types.ts'>events.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/common/types/meeting-colors.types.ts'>meeting-colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/common/types/participant.types.ts'>participant.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/common/types/realtime.types.ts'>realtime.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/common/types/sdk-options.types.ts'>sdk-options.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common/utils</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/common/utils/do-request.ts'>do-request.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/common/utils/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/common/utils/logger.ts'>logger.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/common/utils/observer.ts'>observer.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/common/utils/sleep.ts'>sleep.ts</a></td>
<td><b>0%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/common/utils/sleep.ts#L2>2</a></td></tr><tr><td colspan='5'><b>src/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><b>50%</b></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/components/comments/index.ts'>index.ts</a></td>
<td><b>71.43%</b></td>
<td><b>89.29%</b></td>
<td><b>95.69%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/components/comments/index.ts#L188>188</a>, <a href=https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/components/comments/index.ts#L332>332</a>, <a href=https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/components/comments/index.ts#L332>332</a>, <a href=https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/components/comments/index.ts#L333>333</a>, <a href=https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/components/comments/index.ts#L336>336</a>, <a href=https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/components/comments/index.ts#L77>77</a>, <a href=https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/components/comments/index.ts#L98>98</a></td></tr><tr><td colspan='5'><b>src/components/comments/canvas-pin-adapter</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/components/comments/canvas-pin-adapter/index.ts'>index.ts</a></td>
<td><b>50%</b></td>
<td><span>100%</span></td>
<td><b>97.96%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/components/comments/canvas-pin-adapter/index.ts#L110>110</a>, <a href=https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/components/comments/canvas-pin-adapter/index.ts#L111>111</a>, <a href=https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/components/comments/canvas-pin-adapter/index.ts#L141>141</a></td></tr><tr><td colspan='5'><b>src/components/presence-mouse</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/components/presence-mouse/index.ts'>index.ts</a></td>
<td><b>73.91%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/components/presence-mouse/index.ts#L132>132</a>, <a href=https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/components/presence-mouse/index.ts#L83>83</a>, <a href=https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/components/presence-mouse/index.ts#L90>90</a>, <a href=https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/components/presence-mouse/index.ts#L91>91</a>, <a href=https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/components/presence-mouse/index.ts#L92>92</a>, <a href=https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/components/presence-mouse/index.ts#L93>93</a></td></tr><tr><td colspan='5'><b>src/components/video</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/components/video/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/core</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/core/index.ts'>index.ts</a></td>
<td><b>88.89%</b></td>
<td><span>100%</span></td>
<td><b>87.50%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/core/index.ts#L49>49</a>, <a href=https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/core/index.ts#L50>50</a>, <a href=https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd9 [...]

2023-09-27 23:13 UTC, SuperViz-Dev commented
Total Coverage: <b>99.76%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td colspan='5'><b>src/web-components</b></td></tr><tr><td colspan='5'><b>src/web-components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/base/styles</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/base/styles/icon-button.style.ts'>icon-button.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/base/styles/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/base/styles/sv-hr.style.ts'>sv-hr.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/base/styles/typography.style.ts'>typography.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/base/styles/variables.style.ts'>variables.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/comments/comments.ts'>comments.ts</a></td>
<td><span>100%</span></td>
<td><b>83.33%</b></td>
<td><b>97.14%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/comments/comments.ts#L38>38</a>, <a href=https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/comments/comments.ts#L39>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/comments/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/comments/components/annotation-filter.ts'>annotation-filter.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/comments/components/annotation-item.ts'>annotation-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/comments/components/annotation-pin.ts'>annotation-pin.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/comments/components/annotation-resolved.ts'>annotation-resolved.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/comments/components/annotations.ts'>annotations.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/comments/components/comment-input.ts'>comment-input.ts</a></td>
<td><b>92.59%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/comments/components/comment-input.ts#L41>41</a>, <a href=https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/comments/components/comment-input.ts#L48>48</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/comments/components/comment-item.ts'>comment-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/comments/components/content.ts'>content.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/comments/components/delete-comment-modal.ts'>delete-comment-modal.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/comments/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/comments/components/topbar.ts'>topbar.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/comments/components/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/css</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/comments/css/annotation-filter.style.ts'>annotation-filter.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/comments/css/annotation-item.style.ts'>annotation-item.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/comments/css/annotation-pin.style.ts'>annotation-pin.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/8f94b44a242bfb0d4dadcbc1557dd91c03c0c3b9/src/web-components/comments/css/annotation-resolved.style.ts'>annotation-resolved.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://g [...]

2023-09-27 23:54 UTC, SuperViz-Dev commented
Total Coverage: <b>92.70%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/shims.d.ts'>shims.d.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common</b></td></tr><tr><td colspan='5'><b>src/common/types</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/common/types/events.types.ts'>events.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/common/types/meeting-colors.types.ts'>meeting-colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/common/types/participant.types.ts'>participant.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/common/types/realtime.types.ts'>realtime.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/common/types/sdk-options.types.ts'>sdk-options.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common/utils</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/common/utils/do-request.ts'>do-request.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/common/utils/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/common/utils/logger.ts'>logger.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/common/utils/observer.ts'>observer.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/common/utils/sleep.ts'>sleep.ts</a></td>
<td><b>0%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/common/utils/sleep.ts#L2>2</a></td></tr><tr><td colspan='5'><b>src/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><b>50%</b></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/components/comments/index.ts'>index.ts</a></td>
<td><b>71.43%</b></td>
<td><b>89.29%</b></td>
<td><b>95.76%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/components/comments/index.ts#L104>104</a>, <a href=https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/components/comments/index.ts#L201>201</a>, <a href=https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/components/comments/index.ts#L345>345</a>, <a href=https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/components/comments/index.ts#L345>345</a>, <a href=https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/components/comments/index.ts#L346>346</a>, <a href=https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/components/comments/index.ts#L349>349</a>, <a href=https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/components/comments/index.ts#L83>83</a></td></tr><tr><td colspan='5'><b>src/components/comments/canvas-pin-adapter</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/components/comments/canvas-pin-adapter/index.ts'>index.ts</a></td>
<td><b>50%</b></td>
<td><span>100%</span></td>
<td><b>97.96%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/components/comments/canvas-pin-adapter/index.ts#L110>110</a>, <a href=https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/components/comments/canvas-pin-adapter/index.ts#L111>111</a>, <a href=https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/components/comments/canvas-pin-adapter/index.ts#L141>141</a></td></tr><tr><td colspan='5'><b>src/components/presence-mouse</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/components/presence-mouse/index.ts'>index.ts</a></td>
<td><b>73.91%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/components/presence-mouse/index.ts#L132>132</a>, <a href=https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/components/presence-mouse/index.ts#L83>83</a>, <a href=https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/components/presence-mouse/index.ts#L90>90</a>, <a href=https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/components/presence-mouse/index.ts#L91>91</a>, <a href=https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/components/presence-mouse/index.ts#L92>92</a>, <a href=https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/components/presence-mouse/index.ts#L93>93</a></td></tr><tr><td colspan='5'><b>src/components/video</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/components/video/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/core</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/core/index.ts'>index.ts</a></td>
<td><b>88.89%</b></td>
<td><span>100%</span></td>
<td><b>87.50%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/core/index.ts#L49>49</a>, <a href=https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/core/index.ts#L50>50</a>, <a href=https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d [...]

2023-09-27 23:55 UTC, SuperViz-Dev commented
Total Coverage: <b>99.76%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td colspan='5'><b>src/web-components</b></td></tr><tr><td colspan='5'><b>src/web-components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/base/styles</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/base/styles/icon-button.style.ts'>icon-button.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/base/styles/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/base/styles/sv-hr.style.ts'>sv-hr.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/base/styles/typography.style.ts'>typography.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/base/styles/variables.style.ts'>variables.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/comments/comments.ts'>comments.ts</a></td>
<td><span>100%</span></td>
<td><b>83.33%</b></td>
<td><b>97.10%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/comments/comments.ts#L38>38</a>, <a href=https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/comments/comments.ts#L39>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/comments/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/comments/components/annotation-filter.ts'>annotation-filter.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/comments/components/annotation-item.ts'>annotation-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/comments/components/annotation-pin.ts'>annotation-pin.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/comments/components/annotation-resolved.ts'>annotation-resolved.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/comments/components/annotations.ts'>annotations.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/comments/components/comment-input.ts'>comment-input.ts</a></td>
<td><b>92.59%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/comments/components/comment-input.ts#L41>41</a>, <a href=https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/comments/components/comment-input.ts#L48>48</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/comments/components/comment-item.ts'>comment-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/comments/components/content.ts'>content.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/comments/components/delete-comment-modal.ts'>delete-comment-modal.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/comments/components/float-button.ts'>float-button.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/comments/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/comments/components/topbar.ts'>topbar.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/comments/components/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/css</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/comments/css/annotation-filter.style.ts'>annotation-filter.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/comments/css/annotation-item.style.ts'>annotation-item.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/1ca550f9215d3eb8a3ac717ed00d8eec368e29b5/src/web-components/comments/css/annotation-pin.style.ts'>annotation-pin.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/ [...]

2023-09-28 02:15 UTC, SuperViz-Dev commented
Total Coverage: <b>91.78%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/shims.d.ts'>shims.d.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common</b></td></tr><tr><td colspan='5'><b>src/common/types</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/common/types/events.types.ts'>events.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/common/types/meeting-colors.types.ts'>meeting-colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/common/types/participant.types.ts'>participant.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/common/types/realtime.types.ts'>realtime.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/common/types/sdk-options.types.ts'>sdk-options.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common/utils</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/common/utils/do-request.ts'>do-request.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/common/utils/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/common/utils/logger.ts'>logger.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/common/utils/observer.ts'>observer.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/common/utils/sleep.ts'>sleep.ts</a></td>
<td><b>0%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/common/utils/sleep.ts#L2>2</a></td></tr><tr><td colspan='5'><b>src/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><b>50%</b></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/index.ts'>index.ts</a></td>
<td><b>83.33%</b></td>
<td><b>89.29%</b></td>
<td><b>96%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/index.ts#L102>102</a>, <a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/index.ts#L115>115</a>, <a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/index.ts#L347>347</a>, <a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/index.ts#L347>347</a>, <a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/index.ts#L348>348</a>, <a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/index.ts#L351>351</a></td></tr><tr><td colspan='5'><b>src/components/comments/canvas-pin-adapter</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/canvas-pin-adapter/index.ts'>index.ts</a></td>
<td><b>36.36%</b></td>
<td><b>69.23%</b></td>
<td><b>73.13%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/canvas-pin-adapter/index.ts#L114>114</a>, <a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/canvas-pin-adapter/index.ts#L115>115</a>, <a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/canvas-pin-adapter/index.ts#L117>117</a>, <a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/canvas-pin-adapter/index.ts#L117>117</a>, <a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/canvas-pin-adapter/index.ts#L117>117</a>, <a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/canvas-pin-adapter/index.ts#L117>117</a>, <a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/canvas-pin-adapter/index.ts#L119>119</a>, <a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/canvas-pin-adapter/index.ts#L121>121</a>, <a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/canvas-pin-adapter/index.ts#L122>122</a>, <a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/canvas-pin-adapter/index.ts#L123>123</a>, <a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/canvas-pin-adapter/index.ts#L124>124</a>, <a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/canvas-pin-adapter/index.ts#L125>125</a>, <a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/canvas-pin-adapter/index.ts#L127>127</a>, <a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/canvas-pin-adapter/index.ts#L161>161</a>, <a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/canvas-pin-adapter/index.ts#L163>163</a>, <a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/canvas-pin-adapter/index.ts#L163>163</a>, <a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/components/comments/canvas-pin-adapter/index.ts#L164>164</a>, <a href=https://github.com/SuperViz/sdk/b [...]

2023-09-28 02:15 UTC, SuperViz-Dev commented
Total Coverage: <b>99.73%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td colspan='5'><b>src/web-components</b></td></tr><tr><td colspan='5'><b>src/web-components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/base/styles</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/base/styles/icon-button.style.ts'>icon-button.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/base/styles/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/base/styles/sv-hr.style.ts'>sv-hr.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/base/styles/typography.style.ts'>typography.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/base/styles/variables.style.ts'>variables.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/comments/comments.ts'>comments.ts</a></td>
<td><span>100%</span></td>
<td><b>83.33%</b></td>
<td><b>97.10%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/comments/comments.ts#L38>38</a>, <a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/comments/comments.ts#L39>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/comments/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/comments/components/annotation-filter.ts'>annotation-filter.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/comments/components/annotation-item.ts'>annotation-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/comments/components/annotation-pin.ts'>annotation-pin.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/comments/components/annotation-resolved.ts'>annotation-resolved.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/comments/components/annotations.ts'>annotations.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/comments/components/comment-input.ts'>comment-input.ts</a></td>
<td><b>96.77%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/comments/components/comment-input.ts#L56>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/comments/components/comment-item.ts'>comment-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/comments/components/content.ts'>content.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>98.75%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/comments/components/content.ts#L75>75</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/comments/components/delete-comment-modal.ts'>delete-comment-modal.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/comments/components/float-button.ts'>float-button.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/comments/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/comments/components/topbar.ts'>topbar.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/comments/components/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/css</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/comments/css/annotation-filter.style.ts'>annotation-filter.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/comments/css/annotation-item.style.ts'>annotation-item.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956770df70e2a958505768045c3f73c3a43f4df8/src/web-components/comments/css/annotation-pin.style.ts'>annotation-pin.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/956 [...]

2023-09-28 16:30 UTC, SuperViz-Dev commented
Total Coverage: <b>92.67%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/shims.d.ts'>shims.d.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common</b></td></tr><tr><td colspan='5'><b>src/common/types</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/common/types/events.types.ts'>events.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/common/types/meeting-colors.types.ts'>meeting-colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/common/types/participant.types.ts'>participant.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/common/types/realtime.types.ts'>realtime.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/common/types/sdk-options.types.ts'>sdk-options.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common/utils</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/common/utils/do-request.ts'>do-request.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/common/utils/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/common/utils/logger.ts'>logger.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/common/utils/observer.ts'>observer.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/common/utils/sleep.ts'>sleep.ts</a></td>
<td><b>0%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/common/utils/sleep.ts#L2>2</a></td></tr><tr><td colspan='5'><b>src/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><b>50%</b></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/comments/index.ts'>index.ts</a></td>
<td><b>83.33%</b></td>
<td><b>89.29%</b></td>
<td><b>96.03%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/comments/index.ts#L102>102</a>, <a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/comments/index.ts#L115>115</a>, <a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/comments/index.ts#L348>348</a>, <a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/comments/index.ts#L348>348</a>, <a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/comments/index.ts#L349>349</a>, <a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/comments/index.ts#L352>352</a></td></tr><tr><td colspan='5'><b>src/components/comments/canvas-pin-adapter</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/comments/canvas-pin-adapter/index.ts'>index.ts</a></td>
<td><b>76.92%</b></td>
<td><b>93.33%</b></td>
<td><b>94.32%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/comments/canvas-pin-adapter/index.ts#L165>165</a>, <a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/comments/canvas-pin-adapter/index.ts#L166>166</a>, <a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/comments/canvas-pin-adapter/index.ts#L212>212</a>, <a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/comments/canvas-pin-adapter/index.ts#L214>214</a>, <a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/comments/canvas-pin-adapter/index.ts#L214>214</a>, <a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/comments/canvas-pin-adapter/index.ts#L215>215</a>, <a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/comments/canvas-pin-adapter/index.ts#L218>218</a>, <a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/comments/canvas-pin-adapter/index.ts#L245>245</a></td></tr><tr><td colspan='5'><b>src/components/presence-mouse</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/presence-mouse/index.ts'>index.ts</a></td>
<td><b>73.91%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/presence-mouse/index.ts#L132>132</a>, <a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/presence-mouse/index.ts#L83>83</a>, <a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/presence-mouse/index.ts#L90>90</a>, <a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/presence-mouse/index.ts#L91>91</a>, <a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/presence-mouse/index.ts#L92>92</a>, <a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/presence-mouse/index.ts#L93>93</a></td></tr><tr><td colspan='5'><b>src/components/video</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/components/video/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>10 [...]

2023-09-28 16:31 UTC, SuperViz-Dev commented
Total Coverage: <b>99.73%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td colspan='5'><b>src/web-components</b></td></tr><tr><td colspan='5'><b>src/web-components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/base/styles</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/base/styles/icon-button.style.ts'>icon-button.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/base/styles/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/base/styles/sv-hr.style.ts'>sv-hr.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/base/styles/typography.style.ts'>typography.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/base/styles/variables.style.ts'>variables.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/comments/comments.ts'>comments.ts</a></td>
<td><span>100%</span></td>
<td><b>83.33%</b></td>
<td><b>97.10%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/comments/comments.ts#L38>38</a>, <a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/comments/comments.ts#L39>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/comments/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/comments/components/annotation-filter.ts'>annotation-filter.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/comments/components/annotation-item.ts'>annotation-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/comments/components/annotation-pin.ts'>annotation-pin.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/comments/components/annotation-resolved.ts'>annotation-resolved.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/comments/components/annotations.ts'>annotations.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/comments/components/comment-input.ts'>comment-input.ts</a></td>
<td><b>96.77%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/comments/components/comment-input.ts#L56>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/comments/components/comment-item.ts'>comment-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/comments/components/content.ts'>content.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>98.75%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/comments/components/content.ts#L75>75</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/comments/components/delete-comment-modal.ts'>delete-comment-modal.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/comments/components/float-button.ts'>float-button.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/comments/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/comments/components/topbar.ts'>topbar.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/comments/components/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/css</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/comments/css/annotation-filter.style.ts'>annotation-filter.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/comments/css/annotation-item.style.ts'>annotation-item.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e543c6eccb391e2183efe64af94c88987390bf/src/web-components/comments/css/annotation-pin.style.ts'>annotation-pin.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/84e [...]

2023-09-28 18:14 UTC, SuperViz-Dev commented
Total Coverage: <b>92.87%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/shims.d.ts'>shims.d.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common</b></td></tr><tr><td colspan='5'><b>src/common/types</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/common/types/events.types.ts'>events.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/common/types/meeting-colors.types.ts'>meeting-colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/common/types/participant.types.ts'>participant.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/common/types/realtime.types.ts'>realtime.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/common/types/sdk-options.types.ts'>sdk-options.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common/utils</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/common/utils/do-request.ts'>do-request.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/common/utils/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/common/utils/logger.ts'>logger.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/common/utils/observer.ts'>observer.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/common/utils/sleep.ts'>sleep.ts</a></td>
<td><b>0%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/common/utils/sleep.ts#L2>2</a></td></tr><tr><td colspan='5'><b>src/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><b>50%</b></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/components/comments/index.ts'>index.ts</a></td>
<td><b>83.33%</b></td>
<td><b>92.86%</b></td>
<td><b>96.88%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/components/comments/index.ts#L103>103</a>, <a href=https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/components/comments/index.ts#L367>367</a>, <a href=https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/components/comments/index.ts#L367>367</a>, <a href=https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/components/comments/index.ts#L368>368</a>, <a href=https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/components/comments/index.ts#L371>371</a></td></tr><tr><td colspan='5'><b>src/components/comments/canvas-pin-adapter</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/components/comments/canvas-pin-adapter/index.ts'>index.ts</a></td>
<td><b>85.71%</b></td>
<td><b>94.44%</b></td>
<td><b>96.23%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/components/comments/canvas-pin-adapter/index.ts#L251>251</a>, <a href=https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/components/comments/canvas-pin-adapter/index.ts#L253>253</a>, <a href=https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/components/comments/canvas-pin-adapter/index.ts#L253>253</a>, <a href=https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/components/comments/canvas-pin-adapter/index.ts#L254>254</a>, <a href=https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/components/comments/canvas-pin-adapter/index.ts#L257>257</a>, <a href=https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/components/comments/canvas-pin-adapter/index.ts#L284>284</a></td></tr><tr><td colspan='5'><b>src/components/presence-mouse</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/components/presence-mouse/index.ts'>index.ts</a></td>
<td><b>73.91%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/components/presence-mouse/index.ts#L132>132</a>, <a href=https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/components/presence-mouse/index.ts#L83>83</a>, <a href=https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/components/presence-mouse/index.ts#L90>90</a>, <a href=https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/components/presence-mouse/index.ts#L91>91</a>, <a href=https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/components/presence-mouse/index.ts#L92>92</a>, <a href=https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/components/presence-mouse/index.ts#L93>93</a></td></tr><tr><td colspan='5'><b>src/components/video</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/components/video/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/core</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/core/index.ts'>index.ts</a></td>
<td><b>88.89%</b></td>
<td><span>100%</span></td>
<td><b>87.50%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/154fa1073cf44295862e4a7f9e7758d9ccff213b/src/core/index.ts#L49>49</a> [...]

2023-09-28 18:29 UTC, SuperViz-Dev commented
Total Coverage: <b>99.73%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td colspan='5'><b>src/web-components</b></td></tr><tr><td colspan='5'><b>src/web-components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/base/styles</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/base/styles/icon-button.style.ts'>icon-button.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/base/styles/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/base/styles/sv-hr.style.ts'>sv-hr.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/base/styles/typography.style.ts'>typography.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/base/styles/variables.style.ts'>variables.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/comments/comments.ts'>comments.ts</a></td>
<td><span>100%</span></td>
<td><b>83.33%</b></td>
<td><b>97.10%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/comments/comments.ts#L38>38</a>, <a href=https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/comments/comments.ts#L39>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/comments/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/comments/components/annotation-filter.ts'>annotation-filter.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/comments/components/annotation-item.ts'>annotation-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/comments/components/annotation-pin.ts'>annotation-pin.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/comments/components/annotation-resolved.ts'>annotation-resolved.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/comments/components/annotations.ts'>annotations.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/comments/components/comment-input.ts'>comment-input.ts</a></td>
<td><b>96.77%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/comments/components/comment-input.ts#L56>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/comments/components/comment-item.ts'>comment-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/comments/components/content.ts'>content.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>98.75%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/comments/components/content.ts#L75>75</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/comments/components/delete-comment-modal.ts'>delete-comment-modal.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/comments/components/float-button.ts'>float-button.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/comments/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/comments/components/topbar.ts'>topbar.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/comments/components/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/css</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/comments/css/annotation-filter.style.ts'>annotation-filter.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/comments/css/annotation-item.style.ts'>annotation-item.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/web-components/comments/css/annotation-pin.style.ts'>annotation-pin.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/863 [...]

2023-09-28 18:32 UTC, SuperViz-Dev commented
Total Coverage: <b>92.87%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/shims.d.ts'>shims.d.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common</b></td></tr><tr><td colspan='5'><b>src/common/types</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/common/types/events.types.ts'>events.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/common/types/meeting-colors.types.ts'>meeting-colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/common/types/participant.types.ts'>participant.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/common/types/realtime.types.ts'>realtime.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/common/types/sdk-options.types.ts'>sdk-options.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common/utils</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/common/utils/do-request.ts'>do-request.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/common/utils/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/common/utils/logger.ts'>logger.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/common/utils/observer.ts'>observer.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/common/utils/sleep.ts'>sleep.ts</a></td>
<td><b>0%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/common/utils/sleep.ts#L2>2</a></td></tr><tr><td colspan='5'><b>src/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><b>50%</b></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/components/comments/index.ts'>index.ts</a></td>
<td><b>83.33%</b></td>
<td><b>92.86%</b></td>
<td><b>96.88%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/components/comments/index.ts#L103>103</a>, <a href=https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/components/comments/index.ts#L367>367</a>, <a href=https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/components/comments/index.ts#L367>367</a>, <a href=https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/components/comments/index.ts#L368>368</a>, <a href=https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/components/comments/index.ts#L371>371</a></td></tr><tr><td colspan='5'><b>src/components/comments/canvas-pin-adapter</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/components/comments/canvas-pin-adapter/index.ts'>index.ts</a></td>
<td><b>85.71%</b></td>
<td><b>94.44%</b></td>
<td><b>96.23%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/components/comments/canvas-pin-adapter/index.ts#L251>251</a>, <a href=https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/components/comments/canvas-pin-adapter/index.ts#L253>253</a>, <a href=https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/components/comments/canvas-pin-adapter/index.ts#L253>253</a>, <a href=https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/components/comments/canvas-pin-adapter/index.ts#L254>254</a>, <a href=https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/components/comments/canvas-pin-adapter/index.ts#L257>257</a>, <a href=https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/components/comments/canvas-pin-adapter/index.ts#L284>284</a></td></tr><tr><td colspan='5'><b>src/components/presence-mouse</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/components/presence-mouse/index.ts'>index.ts</a></td>
<td><b>73.91%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/components/presence-mouse/index.ts#L132>132</a>, <a href=https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/components/presence-mouse/index.ts#L83>83</a>, <a href=https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/components/presence-mouse/index.ts#L90>90</a>, <a href=https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/components/presence-mouse/index.ts#L91>91</a>, <a href=https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/components/presence-mouse/index.ts#L92>92</a>, <a href=https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/components/presence-mouse/index.ts#L93>93</a></td></tr><tr><td colspan='5'><b>src/components/video</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/components/video/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/core</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/core/index.ts'>index.ts</a></td>
<td><b>88.89%</b></td>
<td><span>100%</span></td>
<td><b>87.50%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/86352f2b3a1da97e684055ae5b5a9fa5b3679153/src/core/index.ts#L49>49</a> [...]

2023-09-30 14:47 UTC, SuperViz-Dev commented
Total Coverage: <b>92.92%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/shims.d.ts'>shims.d.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common</b></td></tr><tr><td colspan='5'><b>src/common/types</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/common/types/events.types.ts'>events.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/common/types/meeting-colors.types.ts'>meeting-colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/common/types/participant.types.ts'>participant.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/common/types/realtime.types.ts'>realtime.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/common/types/sdk-options.types.ts'>sdk-options.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common/utils</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/common/utils/do-request.ts'>do-request.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/common/utils/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/common/utils/logger.ts'>logger.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/common/utils/observer.ts'>observer.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/common/utils/sleep.ts'>sleep.ts</a></td>
<td><b>0%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/common/utils/sleep.ts#L2>2</a></td></tr><tr><td colspan='5'><b>src/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><b>50%</b></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/components/comments/index.ts'>index.ts</a></td>
<td><b>83.33%</b></td>
<td><b>92.86%</b></td>
<td><b>96.90%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/components/comments/index.ts#L103>103</a>, <a href=https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/components/comments/index.ts#L375>375</a>, <a href=https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/components/comments/index.ts#L375>375</a>, <a href=https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/components/comments/index.ts#L376>376</a>, <a href=https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/components/comments/index.ts#L379>379</a></td></tr><tr><td colspan='5'><b>src/components/comments/canvas-pin-adapter</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/components/comments/canvas-pin-adapter/index.ts'>index.ts</a></td>
<td><b>82.35%</b></td>
<td><b>95%</b></td>
<td><b>96.58%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/components/comments/canvas-pin-adapter/index.ts#L229>229</a>, <a href=https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/components/comments/canvas-pin-adapter/index.ts#L271>271</a>, <a href=https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/components/comments/canvas-pin-adapter/index.ts#L273>273</a>, <a href=https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/components/comments/canvas-pin-adapter/index.ts#L273>273</a>, <a href=https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/components/comments/canvas-pin-adapter/index.ts#L274>274</a>, <a href=https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/components/comments/canvas-pin-adapter/index.ts#L277>277</a>, <a href=https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/components/comments/canvas-pin-adapter/index.ts#L304>304</a></td></tr><tr><td colspan='5'><b>src/components/presence-mouse</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/components/presence-mouse/index.ts'>index.ts</a></td>
<td><b>73.91%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/components/presence-mouse/index.ts#L132>132</a>, <a href=https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/components/presence-mouse/index.ts#L83>83</a>, <a href=https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/components/presence-mouse/index.ts#L90>90</a>, <a href=https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/components/presence-mouse/index.ts#L91>91</a>, <a href=https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/components/presence-mouse/index.ts#L92>92</a>, <a href=https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/components/presence-mouse/index.ts#L93>93</a></td></tr><tr><td colspan='5'><b>src/components/video</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/components/video/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/core</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/core/index.ts'>index.ts</a></td>
<td><b>88.89%</b></td>
<td><span>100%</spa [...]

2023-09-30 14:47 UTC, SuperViz-Dev commented
Total Coverage: <b>99.73%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td colspan='5'><b>src/web-components</b></td></tr><tr><td colspan='5'><b>src/web-components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/base/styles</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/base/styles/icon-button.style.ts'>icon-button.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/base/styles/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/base/styles/sv-hr.style.ts'>sv-hr.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/base/styles/typography.style.ts'>typography.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/base/styles/variables.style.ts'>variables.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/comments/comments.ts'>comments.ts</a></td>
<td><span>100%</span></td>
<td><b>83.33%</b></td>
<td><b>97.10%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/comments/comments.ts#L38>38</a>, <a href=https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/comments/comments.ts#L39>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/comments/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/comments/components/annotation-filter.ts'>annotation-filter.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/comments/components/annotation-item.ts'>annotation-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/comments/components/annotation-pin.ts'>annotation-pin.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/comments/components/annotation-resolved.ts'>annotation-resolved.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/comments/components/annotations.ts'>annotations.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/comments/components/comment-input.ts'>comment-input.ts</a></td>
<td><b>96.77%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/comments/components/comment-input.ts#L56>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/comments/components/comment-item.ts'>comment-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/comments/components/content.ts'>content.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>98.90%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/comments/components/content.ts#L86>86</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/comments/components/delete-comment-modal.ts'>delete-comment-modal.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/comments/components/float-button.ts'>float-button.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/comments/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/comments/components/topbar.ts'>topbar.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/comments/components/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/css</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/comments/css/annotation-filter.style.ts'>annotation-filter.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/comments/css/annotation-item.style.ts'>annotation-item.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab9481f0b824b9ffaf4f257c9373b637e885d27/src/web-components/comments/css/annotation-pin.style.ts'>annotation-pin.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/5ab [...]

2023-10-02 13:31 UTC, vitorvargasdev requested changes

2023-10-02 13:31 UTC, vitorvargasdev commented on src/web-components/comments/components/annotation-pin.ts
> +import { CSSResultGroup, LitElement, PropertyValueMap, html } from 'lit';
PropertyValueMap is not been used
```suggestion
import { CSSResultGroup, LitElement, html } from 'lit';
```

2023-10-02 13:31 UTC, vitorvargasdev commented on src/components/comments/canvas-pin-adapter/index.test.ts
> +
sleep is not used.

2023-10-02 13:31 UTC, vitorvargasdev commented on src/web-components/comments/components/types.ts
> +}
Why is 'SHOW' in uppercase while 'add' is in lowercase? Wouldn't it be better to use all lowercase?
```suggestion
export enum PinMode {
  ADD = 'add',
  SHOW = 'show',
}
```

2023-10-02 13:36 UTC, SuperViz-Dev commented
Total Coverage: <b>92.92%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/shims.d.ts'>shims.d.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common</b></td></tr><tr><td colspan='5'><b>src/common/types</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/common/types/events.types.ts'>events.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/common/types/meeting-colors.types.ts'>meeting-colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/common/types/participant.types.ts'>participant.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/common/types/realtime.types.ts'>realtime.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/common/types/sdk-options.types.ts'>sdk-options.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common/utils</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/common/utils/do-request.ts'>do-request.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/common/utils/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/common/utils/logger.ts'>logger.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/common/utils/observer.ts'>observer.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/common/utils/sleep.ts'>sleep.ts</a></td>
<td><b>0%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/common/utils/sleep.ts#L2>2</a></td></tr><tr><td colspan='5'><b>src/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><b>50%</b></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/components/comments/index.ts'>index.ts</a></td>
<td><b>83.33%</b></td>
<td><b>92.86%</b></td>
<td><b>96.90%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/components/comments/index.ts#L103>103</a>, <a href=https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/components/comments/index.ts#L375>375</a>, <a href=https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/components/comments/index.ts#L375>375</a>, <a href=https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/components/comments/index.ts#L376>376</a>, <a href=https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/components/comments/index.ts#L379>379</a></td></tr><tr><td colspan='5'><b>src/components/comments/canvas-pin-adapter</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/components/comments/canvas-pin-adapter/index.ts'>index.ts</a></td>
<td><b>82.35%</b></td>
<td><b>95%</b></td>
<td><b>96.58%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/components/comments/canvas-pin-adapter/index.ts#L229>229</a>, <a href=https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/components/comments/canvas-pin-adapter/index.ts#L271>271</a>, <a href=https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/components/comments/canvas-pin-adapter/index.ts#L273>273</a>, <a href=https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/components/comments/canvas-pin-adapter/index.ts#L273>273</a>, <a href=https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/components/comments/canvas-pin-adapter/index.ts#L274>274</a>, <a href=https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/components/comments/canvas-pin-adapter/index.ts#L277>277</a>, <a href=https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/components/comments/canvas-pin-adapter/index.ts#L304>304</a></td></tr><tr><td colspan='5'><b>src/components/presence-mouse</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/components/presence-mouse/index.ts'>index.ts</a></td>
<td><b>73.91%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/components/presence-mouse/index.ts#L132>132</a>, <a href=https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/components/presence-mouse/index.ts#L83>83</a>, <a href=https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/components/presence-mouse/index.ts#L90>90</a>, <a href=https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/components/presence-mouse/index.ts#L91>91</a>, <a href=https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/components/presence-mouse/index.ts#L92>92</a>, <a href=https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/components/presence-mouse/index.ts#L93>93</a></td></tr><tr><td colspan='5'><b>src/components/video</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/components/video/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/core</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/core/index.ts'>index.ts</a></td>
<td><b>88.89%</b></td>
<td><span>100%</spa [...]

2023-10-02 13:36 UTC, SuperViz-Dev commented
Total Coverage: <b>99.73%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td colspan='5'><b>src/web-components</b></td></tr><tr><td colspan='5'><b>src/web-components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/base/styles</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/base/styles/icon-button.style.ts'>icon-button.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/base/styles/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/base/styles/sv-hr.style.ts'>sv-hr.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/base/styles/typography.style.ts'>typography.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/base/styles/variables.style.ts'>variables.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/comments/comments.ts'>comments.ts</a></td>
<td><span>100%</span></td>
<td><b>83.33%</b></td>
<td><b>97.10%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/comments/comments.ts#L38>38</a>, <a href=https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/comments/comments.ts#L39>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/comments/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/comments/components/annotation-filter.ts'>annotation-filter.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/comments/components/annotation-item.ts'>annotation-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/comments/components/annotation-pin.ts'>annotation-pin.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/comments/components/annotation-resolved.ts'>annotation-resolved.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/comments/components/annotations.ts'>annotations.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/comments/components/comment-input.ts'>comment-input.ts</a></td>
<td><b>96.77%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/comments/components/comment-input.ts#L56>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/comments/components/comment-item.ts'>comment-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/comments/components/content.ts'>content.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>98.90%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/comments/components/content.ts#L86>86</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/comments/components/delete-comment-modal.ts'>delete-comment-modal.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/comments/components/float-button.ts'>float-button.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/comments/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/comments/components/topbar.ts'>topbar.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/comments/components/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/css</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/comments/css/annotation-filter.style.ts'>annotation-filter.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/comments/css/annotation-item.style.ts'>annotation-item.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b67ca954651c5dd22c26afd5ae11a7828b71c2a/src/web-components/comments/css/annotation-pin.style.ts'>annotation-pin.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/3b6 [...]

2023-10-02 13:43 UTC, vitorvargasdev approved these changes

2023-10-02 16:17 UTC, merged

2023-11-08 15:43 UTC, SuperViz-Dev commented
:tada: This PR is included in version 4.15.0 :tada:

The release is available on:
- [GitHub release](https://github.com/SuperViz/sdk/releases/tag/v4.15.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@superviz/sdk/v/4.15.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: