refactor: participant object in the inicialization
SuperViz/sdk pull request #350
Opened 2023-10-02 18:21 UTC by carlossantos74

2023-10-02 18:22 UTC, SuperViz-Dev commented
Total Coverage: <b>97.84%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td colspan='5'><b>src/web-components</b></td></tr><tr><td colspan='5'><b>src/web-components/hello-world</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/hello-world/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/presence-mouse</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/presence-mouse/index.ts'>index.ts</a></td>
<td><b>66.67%</b></td>
<td><span>100%</span></td>
<td><b>96.33%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/presence-mouse/index.ts#L42>42</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/presence-mouse/index.ts#L43>43</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/presence-mouse/index.ts#L44>44</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/presence-mouse/index.ts#L59>59</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/presence-mouse/index.ts#L60>60</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/presence-mouse/index.ts#L69>69</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/presence-mouse/index.ts#L70>70</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/presence-mouse/index.ts#L76>76</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/presence-mouse/index.ts#L77>77</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/presence-mouse/styles.ts'>styles.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr>
			</tbody>
		</table>
		
</details>

2023-10-02 19:15 UTC, SuperViz-Dev commented
Total Coverage: <b>97.84%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td colspan='5'><b>src/web-components</b></td></tr><tr><td colspan='5'><b>src/web-components/hello-world</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/web-components/hello-world/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/presence-mouse</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/web-components/presence-mouse/index.ts'>index.ts</a></td>
<td><b>66.67%</b></td>
<td><span>100%</span></td>
<td><b>96.33%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/web-components/presence-mouse/index.ts#L42>42</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/web-components/presence-mouse/index.ts#L43>43</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/web-components/presence-mouse/index.ts#L44>44</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/web-components/presence-mouse/index.ts#L59>59</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/web-components/presence-mouse/index.ts#L60>60</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/web-components/presence-mouse/index.ts#L69>69</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/web-components/presence-mouse/index.ts#L70>70</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/web-components/presence-mouse/index.ts#L76>76</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/web-components/presence-mouse/index.ts#L77>77</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/web-components/presence-mouse/styles.ts'>styles.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr>
			</tbody>
		</table>
		
</details>

2023-10-02 19:15 UTC, SuperViz-Dev commented
Total Coverage: <b>92.74%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/shims.d.ts'>shims.d.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common</b></td></tr><tr><td colspan='5'><b>src/common/types</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/common/types/events.types.ts'>events.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/common/types/meeting-colors.types.ts'>meeting-colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/common/types/participant.types.ts'>participant.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/common/types/realtime.types.ts'>realtime.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/common/types/sdk-options.types.ts'>sdk-options.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common/utils</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/common/utils/do-request.ts'>do-request.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/common/utils/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/common/utils/logger.ts'>logger.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/common/utils/observer.ts'>observer.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/common/utils/sleep.ts'>sleep.ts</a></td>
<td><b>0%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/common/utils/sleep.ts#L2>2</a></td></tr><tr><td colspan='5'><b>src/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><b>50%</b></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/components/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/presence-mouse</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/components/presence-mouse/index.ts'>index.ts</a></td>
<td><b>73.91%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/components/presence-mouse/index.ts#L133>133</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/components/presence-mouse/index.ts#L84>84</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/components/presence-mouse/index.ts#L91>91</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/components/presence-mouse/index.ts#L92>92</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/components/presence-mouse/index.ts#L93>93</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/components/presence-mouse/index.ts#L94>94</a></td></tr><tr><td colspan='5'><b>src/components/video</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/components/video/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/core</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/core/index.ts'>index.ts</a></td>
<td><b>80%</b></td>
<td><span>100%</span></td>
<td><b>88.24%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/core/index.ts#L49>49</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/core/index.ts#L50>50</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/core/index.ts#L68>68</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/core/index.ts#L72>72</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/core/index.ts#L74>74</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/core/index.ts#L85>85</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/core/index.ts#L89>89</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/core/index.ts#L89>89</a></td></tr><tr><td colspan='5'><b>src/core/launcher</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/core/launcher/index.ts'>index.ts</a></td>
<td><b>92.31%</b></td>
<td><b>95%</b></td>
<td><b>95.05%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/core/launcher/index.ts#L279>279</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/core/launcher/index.ts#L281>281</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/core/launcher/index.ts#L281>281</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/core/launcher/index.ts#L282>282</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/core/launcher/index.ts#L283>283</a>, <a href=https://github.com/SuperViz/sdk/blob/be4a0ac933942599f966a1d4fb26b3e499dcb80e/src/core/launcher/index.ts#L285>285</a></td></tr><tr><td colspan='5'><b>src/services</b></td></tr><tr><td colspan='5'><b>src/services/api</b></td></tr><t [...]

2023-10-03 11:26 UTC, vitorvargasdev requested changes

2023-10-03 11:26 UTC, vitorvargasdev commented on src/core/launcher/types.ts
> +import { Participant } from '../../common/types/participant.types';
"Participant" is not used

2023-10-03 11:30 UTC, vitorvargasdev approved these changes

2023-10-03 11:30 UTC, SuperViz-Dev commented
Total Coverage: <b>97.84%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td colspan='5'><b>src/web-components</b></td></tr><tr><td colspan='5'><b>src/web-components/hello-world</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/web-components/hello-world/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/presence-mouse</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/web-components/presence-mouse/index.ts'>index.ts</a></td>
<td><b>66.67%</b></td>
<td><span>100%</span></td>
<td><b>96.33%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/web-components/presence-mouse/index.ts#L42>42</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/web-components/presence-mouse/index.ts#L43>43</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/web-components/presence-mouse/index.ts#L44>44</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/web-components/presence-mouse/index.ts#L59>59</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/web-components/presence-mouse/index.ts#L60>60</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/web-components/presence-mouse/index.ts#L69>69</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/web-components/presence-mouse/index.ts#L70>70</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/web-components/presence-mouse/index.ts#L76>76</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/web-components/presence-mouse/index.ts#L77>77</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/web-components/presence-mouse/styles.ts'>styles.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr>
			</tbody>
		</table>
		
</details>

2023-10-03 11:30 UTC, SuperViz-Dev commented
Total Coverage: <b>92.74%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/shims.d.ts'>shims.d.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common</b></td></tr><tr><td colspan='5'><b>src/common/types</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/common/types/events.types.ts'>events.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/common/types/meeting-colors.types.ts'>meeting-colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/common/types/participant.types.ts'>participant.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/common/types/realtime.types.ts'>realtime.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/common/types/sdk-options.types.ts'>sdk-options.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common/utils</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/common/utils/do-request.ts'>do-request.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/common/utils/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/common/utils/logger.ts'>logger.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/common/utils/observer.ts'>observer.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/common/utils/sleep.ts'>sleep.ts</a></td>
<td><b>0%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/common/utils/sleep.ts#L2>2</a></td></tr><tr><td colspan='5'><b>src/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><b>50%</b></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/components/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/presence-mouse</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/components/presence-mouse/index.ts'>index.ts</a></td>
<td><b>73.91%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/components/presence-mouse/index.ts#L133>133</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/components/presence-mouse/index.ts#L84>84</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/components/presence-mouse/index.ts#L91>91</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/components/presence-mouse/index.ts#L92>92</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/components/presence-mouse/index.ts#L93>93</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/components/presence-mouse/index.ts#L94>94</a></td></tr><tr><td colspan='5'><b>src/components/video</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/components/video/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/core</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/core/index.ts'>index.ts</a></td>
<td><b>80%</b></td>
<td><span>100%</span></td>
<td><b>88.24%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/core/index.ts#L49>49</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/core/index.ts#L50>50</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/core/index.ts#L68>68</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/core/index.ts#L72>72</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/core/index.ts#L74>74</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/core/index.ts#L85>85</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/core/index.ts#L89>89</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/core/index.ts#L89>89</a></td></tr><tr><td colspan='5'><b>src/core/launcher</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/core/launcher/index.ts'>index.ts</a></td>
<td><b>92.31%</b></td>
<td><b>95%</b></td>
<td><b>95.05%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/core/launcher/index.ts#L279>279</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/core/launcher/index.ts#L281>281</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/core/launcher/index.ts#L281>281</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/core/launcher/index.ts#L282>282</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/core/launcher/index.ts#L283>283</a>, <a href=https://github.com/SuperViz/sdk/blob/e9b0f031ce577f0d5a99c9dba7252bf67e96105b/src/core/launcher/index.ts#L285>285</a></td></tr><tr><td colspan='5'><b>src/services</b></td></tr><tr><td colspan='5'><b>src/services/api</b></td></tr><t [...]

2023-10-03 11:32 UTC, merged

2023-11-08 15:43 UTC, SuperViz-Dev commented
:tada: This PR is included in version 4.15.0 :tada:

The release is available on:
- [GitHub release](https://github.com/SuperViz/sdk/releases/tag/v4.15.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@superviz/sdk/v/4.15.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: