Feat/add flexibility to comments layout
SuperViz/sdk pull request #392
Opened 2023-10-27 13:04 UTC by Raspincel

2023-10-27 13:07 UTC, SuperViz-Dev commented
Total Coverage: <b>99.38%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td colspan='5'><b>src/web-components</b></td></tr><tr><td colspan='5'><b>src/web-components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/base/styles</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/styles/icon-button.style.ts'>icon-button.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/styles/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/styles/sv-hr.style.ts'>sv-hr.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/styles/typography.style.ts'>typography.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/styles/variables.style.ts'>variables.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/comments.ts'>comments.ts</a></td>
<td><b>92.86%</b></td>
<td><b>87.50%</b></td>
<td><b>98.23%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/comments.ts#L44>44</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/comments.ts#L45>45</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/comments.ts#L61>61</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-filter.ts'>annotation-filter.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-item.ts'>annotation-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-pin.ts'>annotation-pin.ts</a></td>
<td><b>88.89%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-pin.ts#L35>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-resolved.ts'>annotation-resolved.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotations.ts'>annotations.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/comment-input.ts'>comment-input.ts</a></td>
<td><b>96.88%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/comment-input.ts#L56>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/comment-item.ts'>comment-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/content.ts'>content.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>99.19%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/content.ts#L118>118</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/delete-comment-modal.ts'>delete-comment-modal.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/float-button.ts'>float-button.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>96.10%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/float-button.ts#L40>40</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/float-button.ts#L60>60</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/float-button.ts#L61>61</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/topbar.ts'>topbar.ts</a></td>
<td><b>80%</b></td>
<td><span>100%</span></td>
<td><b>80.85%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/topbar.ts#L32>32</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/topbar.ts#L33>33</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/topbar.ts#L34>34</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/topbar.ts#L35>35</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/topbar.ts#L36>36</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/topbar.ts#L37>37</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/topbar.ts#L38>38</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/topbar.ts#L39>39</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/topbar.ts#L40>40</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/topbar.ts#L41>41</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/css</b></td></tr><t [...]

2023-10-27 13:12 UTC, carlossantos74 requested changes

2023-10-27 13:12 UTC, carlossantos74 commented on src/components/comments/index.ts
> +    this.layoutOptions = options;
```suggestion
    this.layoutOptions = options ?? {
      position?: CommentsSide.LEFT;
      buttonLocation:ButtonLocation.TOP_LEFT,
    };
```

2023-10-27 13:12 UTC, carlossantos74 commented on src/components/comments/types.ts
> +    | string;
```suggestion
  position?: CommentsSide | `${CommentsSide}`;
  buttonLocation?: ButtonLocation | `${ButtonLocation}` | string;
```

2023-10-27 13:12 UTC, carlossantos74 commented on src/web-components/comments/components/topbar.ts
> +        `;
```suggestion
     if(this.side === 'left') {
        return  html`
          <div class="topbar">
            <span @click=${this.close} class="toggle-icon">
              <superviz-icon name="left" size="lg"></superviz-icon>
            </span>
            <span class="text text-bold">COMMENTS</span>
          </div>
        `
     }
   
   return html`
          <div class="topbar">
            <span class="text text-bold">COMMENTS</span>
            <span @click=${this.close} class="toggle-icon">
              <superviz-icon name="right" size="lg"></superviz-icon>
            </span>
          </div>
        `;
```

2023-10-29 20:32 UTC, SuperViz-Dev commented
Total Coverage: <b>90.03%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/shims.d.ts'>shims.d.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common</b></td></tr><tr><td colspan='5'><b>src/common/types</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/common/types/events.types.ts'>events.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/common/types/meeting-colors.types.ts'>meeting-colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/common/types/participant.types.ts'>participant.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/common/types/realtime.types.ts'>realtime.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/common/types/sdk-options.types.ts'>sdk-options.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common/utils</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/common/utils/do-request.ts'>do-request.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>87.50%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/common/utils/do-request.ts#L20>20</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/common/utils/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/common/utils/logger.ts'>logger.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/common/utils/observable.ts'>observable.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/common/utils/observer.ts'>observer.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/common/utils/sleep.ts'>sleep.ts</a></td>
<td><b>0%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/common/utils/sleep.ts#L2>2</a></td></tr><tr><td colspan='5'><b>src/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/components/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/components/comments/index.ts'>index.ts</a></td>
<td><b>60%</b></td>
<td><b>96.77%</b></td>
<td><b>96.53%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/components/comments/index.ts#L112>112</a>, <a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/components/comments/index.ts#L178>178</a>, <a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/components/comments/index.ts#L179>179</a>, <a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/components/comments/index.ts#L180>180</a>, <a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/components/comments/index.ts#L187>187</a>, <a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/components/comments/index.ts#L188>188</a>, <a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/components/comments/index.ts#L190>190</a>, <a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/components/comments/index.ts#L190>190</a>, <a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/components/comments/index.ts#L190>190</a>, <a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/components/comments/index.ts#L190>190</a>, <a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/components/comments/index.ts#L191>191</a>, <a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/components/comments/index.ts#L214>214</a>, <a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/components/comments/index.ts#L219>219</a>, <a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/components/comments/index.ts#L221>221</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/components/comments/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments/canvas-pin-adapter</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/components/comments/canvas-pin-adapter/index.ts'>index.ts</a></td>
<td><b>89.47%</b></td>
<td><b>90.48%</b></td>
<td><b>93.18%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/components/comments/canvas-pin-adapter/index.ts#L193>193</a>, <a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/components/comments/canvas-pin-adapter/index.ts#L194>194</a>, <a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/components/comments/canvas-pin-adapter/index.ts#L195>195</a>, <a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/components/comments/canvas-pin-adapter/index.ts#L196>196</a>, <a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a [...]

2023-10-29 20:33 UTC, SuperViz-Dev commented
Total Coverage: <b>99.52%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td colspan='5'><b>src/web-components</b></td></tr><tr><td colspan='5'><b>src/web-components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/base/styles</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/base/styles/icon-button.style.ts'>icon-button.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/base/styles/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/base/styles/sv-hr.style.ts'>sv-hr.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/base/styles/typography.style.ts'>typography.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/base/styles/variables.style.ts'>variables.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/comments.ts'>comments.ts</a></td>
<td><b>92.86%</b></td>
<td><b>87.50%</b></td>
<td><b>98.23%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/comments.ts#L44>44</a>, <a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/comments.ts#L45>45</a>, <a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/comments.ts#L61>61</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/components/annotation-filter.ts'>annotation-filter.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/components/annotation-item.ts'>annotation-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/components/annotation-pin.ts'>annotation-pin.ts</a></td>
<td><b>88.89%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/components/annotation-pin.ts#L35>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/components/annotation-resolved.ts'>annotation-resolved.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/components/annotations.ts'>annotations.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/components/comment-input.ts'>comment-input.ts</a></td>
<td><b>96.88%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/components/comment-input.ts#L56>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/components/comment-item.ts'>comment-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/components/content.ts'>content.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>99.19%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/components/content.ts#L118>118</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/components/delete-comment-modal.ts'>delete-comment-modal.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/components/float-button.ts'>float-button.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>96.10%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/components/float-button.ts#L40>40</a>, <a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/components/float-button.ts#L60>60</a>, <a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/components/float-button.ts#L61>61</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/components/topbar.ts'>topbar.ts</a></td>
<td><b>80%</b></td>
<td><span>100%</span></td>
<td><b>89.80%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/components/topbar.ts#L38>38</a>, <a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/components/topbar.ts#L39>39</a>, <a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/components/topbar.ts#L40>40</a>, <a href=https://github.com/SuperViz/sdk/blob/d66674ec6ab239e3c2a13ab920ce7655f9374936/src/web-components/comments/components/topbar.ts#L4 [...]

2023-10-29 20:50 UTC, SuperViz-Dev commented
Total Coverage: <b>99.52%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td colspan='5'><b>src/web-components</b></td></tr><tr><td colspan='5'><b>src/web-components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/base/styles</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/base/styles/icon-button.style.ts'>icon-button.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/base/styles/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/base/styles/sv-hr.style.ts'>sv-hr.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/base/styles/typography.style.ts'>typography.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/base/styles/variables.style.ts'>variables.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/comments.ts'>comments.ts</a></td>
<td><b>92.86%</b></td>
<td><b>87.50%</b></td>
<td><b>98.23%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/comments.ts#L44>44</a>, <a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/comments.ts#L45>45</a>, <a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/comments.ts#L61>61</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/components/annotation-filter.ts'>annotation-filter.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/components/annotation-item.ts'>annotation-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/components/annotation-pin.ts'>annotation-pin.ts</a></td>
<td><b>88.89%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/components/annotation-pin.ts#L35>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/components/annotation-resolved.ts'>annotation-resolved.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/components/annotations.ts'>annotations.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/components/comment-input.ts'>comment-input.ts</a></td>
<td><b>96.88%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/components/comment-input.ts#L56>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/components/comment-item.ts'>comment-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/components/content.ts'>content.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>99.19%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/components/content.ts#L118>118</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/components/delete-comment-modal.ts'>delete-comment-modal.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/components/float-button.ts'>float-button.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>96.15%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/components/float-button.ts#L41>41</a>, <a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/components/float-button.ts#L61>61</a>, <a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/components/float-button.ts#L62>62</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/components/topbar.ts'>topbar.ts</a></td>
<td><b>80%</b></td>
<td><span>100%</span></td>
<td><b>89.80%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/components/topbar.ts#L38>38</a>, <a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/components/topbar.ts#L39>39</a>, <a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/components/topbar.ts#L40>40</a>, <a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/web-components/comments/components/topbar.ts#L4 [...]

2023-10-29 20:50 UTC, SuperViz-Dev commented
Total Coverage: <b>89.98%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/shims.d.ts'>shims.d.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common</b></td></tr><tr><td colspan='5'><b>src/common/types</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/common/types/events.types.ts'>events.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/common/types/meeting-colors.types.ts'>meeting-colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/common/types/participant.types.ts'>participant.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/common/types/realtime.types.ts'>realtime.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/common/types/sdk-options.types.ts'>sdk-options.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common/utils</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/common/utils/do-request.ts'>do-request.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>87.50%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/common/utils/do-request.ts#L20>20</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/common/utils/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/common/utils/logger.ts'>logger.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/common/utils/observable.ts'>observable.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/common/utils/observer.ts'>observer.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/common/utils/sleep.ts'>sleep.ts</a></td>
<td><b>0%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/common/utils/sleep.ts#L2>2</a></td></tr><tr><td colspan='5'><b>src/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/components/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/components/comments/index.ts'>index.ts</a></td>
<td><b>60%</b></td>
<td><b>96.77%</b></td>
<td><b>95.98%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/components/comments/index.ts#L112>112</a>, <a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/components/comments/index.ts#L178>178</a>, <a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/components/comments/index.ts#L179>179</a>, <a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/components/comments/index.ts#L180>180</a>, <a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/components/comments/index.ts#L181>181</a>, <a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/components/comments/index.ts#L188>188</a>, <a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/components/comments/index.ts#L189>189</a>, <a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/components/comments/index.ts#L191>191</a>, <a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/components/comments/index.ts#L191>191</a>, <a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/components/comments/index.ts#L191>191</a>, <a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/components/comments/index.ts#L191>191</a>, <a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/components/comments/index.ts#L192>192</a>, <a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/components/comments/index.ts#L215>215</a>, <a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/components/comments/index.ts#L220>220</a>, <a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/components/comments/index.ts#L222>222</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/components/comments/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments/canvas-pin-adapter</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/components/comments/canvas-pin-adapter/index.ts'>index.ts</a></td>
<td><b>89.47%</b></td>
<td><b>90.48%</b></td>
<td><b>93.18%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/components/comments/canvas-pin-adapter/index.ts#L193>193</a>, <a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/components/comments/canvas-pin-adapter/index.ts#L194>194</a>, <a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c205/src/components/comments/canvas-pin-adapter/index.ts#L195>195</a>, <a href=https://github.com/SuperViz/sdk/blob/0254c9ebbc45890c1f4daeba762644254d00c2 [...]

2023-10-31 09:59 UTC, SuperViz-Dev commented
Total Coverage: <b>90.50%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/shims.d.ts'>shims.d.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common</b></td></tr><tr><td colspan='5'><b>src/common/types</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/common/types/events.types.ts'>events.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/common/types/meeting-colors.types.ts'>meeting-colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/common/types/participant.types.ts'>participant.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/common/types/realtime.types.ts'>realtime.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/common/types/sdk-options.types.ts'>sdk-options.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common/utils</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/common/utils/do-request.ts'>do-request.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>87.50%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/common/utils/do-request.ts#L20>20</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/common/utils/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/common/utils/logger.ts'>logger.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/common/utils/observable.ts'>observable.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/common/utils/observer.ts'>observer.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/common/utils/sleep.ts'>sleep.ts</a></td>
<td><b>0%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/common/utils/sleep.ts#L2>2</a></td></tr><tr><td colspan='5'><b>src/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/components/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/components/comments/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><b>96.77%</b></td>
<td><b>99.44%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/components/comments/index.ts#L112>112</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/components/comments/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments/canvas-pin-adapter</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/components/comments/canvas-pin-adapter/index.ts'>index.ts</a></td>
<td><b>95.65%</b></td>
<td><b>95.24%</b></td>
<td><b>96.40%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/components/comments/canvas-pin-adapter/index.ts#L193>193</a>, <a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/components/comments/canvas-pin-adapter/index.ts#L194>194</a>, <a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/components/comments/canvas-pin-adapter/index.ts#L195>195</a>, <a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/components/comments/canvas-pin-adapter/index.ts#L196>196</a>, <a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/components/comments/canvas-pin-adapter/index.ts#L197>197</a>, <a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/components/comments/canvas-pin-adapter/index.ts#L340>340</a></td></tr><tr><td colspan='5'><b>src/components/presence-mouse</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/components/presence-mouse/index.ts'>index.ts</a></td>
<td><b>88.89%</b></td>
<td><b>83.33%</b></td>
<td><b>89.19%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/components/presence-mouse/index.ts#L130>130</a>, <a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/components/presence-mouse/index.ts#L131>131</a>, <a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/components/presence-mouse/index.ts#L132>132</a>, <a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/components/presence-mouse/index.ts#L142>142</a>, <a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/components/presence-mouse/index.ts#L177>177</a>, <a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/components/presence-mouse/index.ts#L178>178</a>, <a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/components/presence-mouse/index.ts#L179>179</a>, <a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/components/presence-mouse/index.ts#L180>180</a>, <a href=https://github.com/SuperViz/sdk/blob/91575fad9e9f [...]

2023-10-31 10:00 UTC, SuperViz-Dev commented
Total Coverage: <b>99.31%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td colspan='5'><b>src/web-components</b></td></tr><tr><td colspan='5'><b>src/web-components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/base/styles</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/base/styles/icon-button.style.ts'>icon-button.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/base/styles/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/base/styles/sv-hr.style.ts'>sv-hr.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/base/styles/typography.style.ts'>typography.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/base/styles/variables.style.ts'>variables.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/comments.ts'>comments.ts</a></td>
<td><b>92.86%</b></td>
<td><b>87.50%</b></td>
<td><b>98.23%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/comments.ts#L44>44</a>, <a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/comments.ts#L45>45</a>, <a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/comments.ts#L61>61</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/components/annotation-filter.ts'>annotation-filter.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/components/annotation-item.ts'>annotation-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/components/annotation-pin.ts'>annotation-pin.ts</a></td>
<td><b>88.89%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/components/annotation-pin.ts#L35>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/components/annotation-resolved.ts'>annotation-resolved.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/components/annotations.ts'>annotations.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/components/comment-input.ts'>comment-input.ts</a></td>
<td><b>96.88%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/components/comment-input.ts#L56>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/components/comment-item.ts'>comment-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/components/content.ts'>content.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>99.19%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/components/content.ts#L118>118</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/components/delete-comment-modal.ts'>delete-comment-modal.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/components/float-button.ts'>float-button.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>96.15%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/components/float-button.ts#L41>41</a>, <a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/components/float-button.ts#L61>61</a>, <a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/components/float-button.ts#L62>62</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/components/topbar.ts'>topbar.ts</a></td>
<td><b>80%</b></td>
<td><span>100%</span></td>
<td><b>89.80%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/components/topbar.ts#L38>38</a>, <a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/components/topbar.ts#L39>39</a>, <a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/components/topbar.ts#L40>40</a>, <a href=https://github.com/SuperViz/sdk/blob/91575fad9e9fe0a111f75295a501687a48537278/src/web-components/comments/components/topbar.ts#L4 [...]

2023-10-31 12:36 UTC, carlossantos74 approved these changes

2023-10-31 12:36 UTC, merged

2023-11-08 15:41 UTC, SuperViz-Dev commented
:tada: This PR is included in version 4.15.0 :tada:

The release is available on:
- [GitHub release](https://github.com/SuperViz/sdk/releases/tag/v4.15.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@superviz/sdk/v/4.15.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: