Feat/wio v3
SuperViz/sdk pull request #464
Opened 2023-12-14 16:12 UTC by Raspincel

2023-12-14 16:14 UTC, SuperViz-Dev commented
Total Coverage: <b>98.08%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td colspan='5'><b>src/web-components</b></td></tr><tr><td colspan='5'><b>src/web-components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>80.52%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L29>29</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L30>30</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L43>43</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L44>44</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L45>45</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L46>46</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L47>47</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L48>48</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L49>49</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L50>50</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L51>51</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L52>52</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L53>53</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L54>54</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L55>55</a></td></tr><tr><td colspan='5'><b>src/web-components/base/styles</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/styles/icon-button.style.ts'>icon-button.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/styles/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/styles/sv-hr.style.ts'>sv-hr.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/styles/typography.style.ts'>typography.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/styles/variables.style.ts'>variables.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/comments.ts'>comments.ts</a></td>
<td><b>92.86%</b></td>
<td><b>87.50%</b></td>
<td><b>98.23%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/comments.ts#L44>44</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/comments.ts#L45>45</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/comments.ts#L61>61</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-filter.ts'>annotation-filter.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-item.ts'>annotation-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-pin.ts'>annotation-pin.ts</a></td>
<td><b>88.89%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-pin.ts#L35>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-resolved.ts'>annotation-resolved.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotations.ts'>annotations.ts</a></td>
<td><span>100%</span></td>
<td><b>88.89%</b></td>
<td><b>90.10%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotations.ts#L39>39</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotations.ts#L40>40</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotations.ts#L41>41</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotations.ts#L42>42</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotations.ts#L56>56</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotations.ts#L57>57</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotations.ts#L58>58</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotations.ts#L74>74</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotations.ts#L75>75</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotations.ts#L76>76</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/comment-input.ts'>comment-input.ts</a></td>
<td><b>96.55%</b></td>
<td><b>94.12%</b></td>
<td><b>87.98%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/comment-input.ts#L101>101</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/comment-input.ts#L102>102</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/comment-input.ts#L103>103</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/comment-input.ts#L104>104</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/comment-input.ts#L105>105</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/comment-input.ts#L106>106</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/comment-input.ts#L107>107</a [...]

2023-12-14 23:03 UTC, SuperViz-Dev commented
Total Coverage: <b>92.01%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/shims.d.ts'>shims.d.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common</b></td></tr><tr><td colspan='5'><b>src/common/types</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/common/types/colors.types.ts'>colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/common/types/events.types.ts'>events.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/common/types/meeting-colors.types.ts'>meeting-colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/common/types/participant.types.ts'>participant.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/common/types/realtime.types.ts'>realtime.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/common/types/sdk-options.types.ts'>sdk-options.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common/utils</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/common/utils/do-request.ts'>do-request.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>87.50%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/common/utils/do-request.ts#L20>20</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/common/utils/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/common/utils/logger.ts'>logger.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/common/utils/observable.ts'>observable.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/common/utils/observer.ts'>observer.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/common/utils/sleep.ts'>sleep.ts</a></td>
<td><b>0%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/common/utils/sleep.ts#L2>2</a></td></tr><tr><td colspan='5'><b>src/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/components/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/components/comments/index.ts'>index.ts</a></td>
<td><b>92%</b></td>
<td><b>97.06%</b></td>
<td><b>98.48%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/components/comments/index.ts#L126>126</a>, <a href=https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/components/comments/index.ts#L193>193</a>, <a href=https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/components/comments/index.ts#L447>447</a>, <a href=https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/components/comments/index.ts#L544>544</a>, <a href=https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/components/comments/index.ts#L560>560</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/components/comments/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments/canvas-pin-adapter</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/components/comments/canvas-pin-adapter/index.ts'>index.ts</a></td>
<td><b>65.91%</b></td>
<td><b>96.55%</b></td>
<td><b>93.27%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/components/comments/canvas-pin-adapter/index.ts#L244>244</a>, <a href=https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/components/comments/canvas-pin-adapter/index.ts#L244>244</a>, <a href=https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/components/comments/canvas-pin-adapter/index.ts#L244>244</a>, <a href=https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/components/comments/canvas-pin-adapter/index.ts#L244>244</a>, <a href=https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/components/comments/canvas-pin-adapter/index.ts#L245>245</a>, <a href=https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/components/comments/canvas-pin-adapter/index.ts#L246>246</a>, <a href=https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/components/comments/canvas-pin-adapter/index.ts#L249>249</a>, <a href=https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/components/comments/canvas-pin-adapter/index.ts#L249>249</a>, <a href=https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/components/comments/canvas-pin-adapter/index.ts#L250>250</a>, <a href=https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/src/components/comments/canvas-pin-adapter/index.ts#L253>253</a>, <a href=https://github.com/SuperViz/sdk/blob/f5245d7d57252471ee23dfe59033b29af693bca7/s [...]

2023-12-15 01:37 UTC, SuperViz-Dev commented
Total Coverage: <b>92.02%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/shims.d.ts'>shims.d.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common</b></td></tr><tr><td colspan='5'><b>src/common/types</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/common/types/colors.types.ts'>colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/common/types/events.types.ts'>events.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/common/types/meeting-colors.types.ts'>meeting-colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/common/types/participant.types.ts'>participant.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/common/types/realtime.types.ts'>realtime.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/common/types/sdk-options.types.ts'>sdk-options.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common/utils</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/common/utils/do-request.ts'>do-request.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>87.50%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/common/utils/do-request.ts#L20>20</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/common/utils/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/common/utils/logger.ts'>logger.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/common/utils/observable.ts'>observable.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/common/utils/observer.ts'>observer.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/common/utils/sleep.ts'>sleep.ts</a></td>
<td><b>0%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/common/utils/sleep.ts#L2>2</a></td></tr><tr><td colspan='5'><b>src/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/components/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/components/comments/index.ts'>index.ts</a></td>
<td><b>92%</b></td>
<td><b>97.06%</b></td>
<td><b>98.48%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/components/comments/index.ts#L126>126</a>, <a href=https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/components/comments/index.ts#L193>193</a>, <a href=https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/components/comments/index.ts#L447>447</a>, <a href=https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/components/comments/index.ts#L544>544</a>, <a href=https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/components/comments/index.ts#L560>560</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/components/comments/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments/canvas-pin-adapter</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/components/comments/canvas-pin-adapter/index.ts'>index.ts</a></td>
<td><b>65.91%</b></td>
<td><b>96.55%</b></td>
<td><b>93.27%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/components/comments/canvas-pin-adapter/index.ts#L244>244</a>, <a href=https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/components/comments/canvas-pin-adapter/index.ts#L244>244</a>, <a href=https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/components/comments/canvas-pin-adapter/index.ts#L244>244</a>, <a href=https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/components/comments/canvas-pin-adapter/index.ts#L244>244</a>, <a href=https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/components/comments/canvas-pin-adapter/index.ts#L245>245</a>, <a href=https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/components/comments/canvas-pin-adapter/index.ts#L246>246</a>, <a href=https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/components/comments/canvas-pin-adapter/index.ts#L249>249</a>, <a href=https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/components/comments/canvas-pin-adapter/index.ts#L249>249</a>, <a href=https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/components/comments/canvas-pin-adapter/index.ts#L250>250</a>, <a href=https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/src/components/comments/canvas-pin-adapter/index.ts#L253>253</a>, <a href=https://github.com/SuperViz/sdk/blob/6a296b333bbca75ba910ce93dc78a9d725b1f05f/s [...]

2023-12-15 01:56 UTC, SuperViz-Dev commented
Total Coverage: <b>92.02%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/shims.d.ts'>shims.d.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common</b></td></tr><tr><td colspan='5'><b>src/common/types</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/common/types/colors.types.ts'>colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/common/types/events.types.ts'>events.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/common/types/meeting-colors.types.ts'>meeting-colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/common/types/participant.types.ts'>participant.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/common/types/realtime.types.ts'>realtime.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/common/types/sdk-options.types.ts'>sdk-options.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common/utils</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/common/utils/do-request.ts'>do-request.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>87.50%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/common/utils/do-request.ts#L20>20</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/common/utils/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/common/utils/logger.ts'>logger.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/common/utils/observable.ts'>observable.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/common/utils/observer.ts'>observer.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/common/utils/sleep.ts'>sleep.ts</a></td>
<td><b>0%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/common/utils/sleep.ts#L2>2</a></td></tr><tr><td colspan='5'><b>src/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/components/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/components/comments/index.ts'>index.ts</a></td>
<td><b>92%</b></td>
<td><b>97.06%</b></td>
<td><b>98.48%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/components/comments/index.ts#L126>126</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/components/comments/index.ts#L193>193</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/components/comments/index.ts#L447>447</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/components/comments/index.ts#L544>544</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/components/comments/index.ts#L560>560</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/components/comments/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments/canvas-pin-adapter</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/components/comments/canvas-pin-adapter/index.ts'>index.ts</a></td>
<td><b>65.91%</b></td>
<td><b>96.55%</b></td>
<td><b>93.27%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/components/comments/canvas-pin-adapter/index.ts#L244>244</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/components/comments/canvas-pin-adapter/index.ts#L244>244</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/components/comments/canvas-pin-adapter/index.ts#L244>244</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/components/comments/canvas-pin-adapter/index.ts#L244>244</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/components/comments/canvas-pin-adapter/index.ts#L245>245</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/components/comments/canvas-pin-adapter/index.ts#L246>246</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/components/comments/canvas-pin-adapter/index.ts#L249>249</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/components/comments/canvas-pin-adapter/index.ts#L249>249</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/components/comments/canvas-pin-adapter/index.ts#L250>250</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/components/comments/canvas-pin-adapter/index.ts#L253>253</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/s [...]

2023-12-15 01:57 UTC, SuperViz-Dev commented
Total Coverage: <b>98.04%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td colspan='5'><b>src/web-components</b></td></tr><tr><td colspan='5'><b>src/web-components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>80.52%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/base/index.ts#L29>29</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/base/index.ts#L30>30</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/base/index.ts#L43>43</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/base/index.ts#L44>44</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/base/index.ts#L45>45</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/base/index.ts#L46>46</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/base/index.ts#L47>47</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/base/index.ts#L48>48</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/base/index.ts#L49>49</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/base/index.ts#L50>50</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/base/index.ts#L51>51</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/base/index.ts#L52>52</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/base/index.ts#L53>53</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/base/index.ts#L54>54</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/base/index.ts#L55>55</a></td></tr><tr><td colspan='5'><b>src/web-components/base/styles</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/base/styles/icon-button.style.ts'>icon-button.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/base/styles/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/base/styles/sv-hr.style.ts'>sv-hr.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/base/styles/typography.style.ts'>typography.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/base/styles/variables.style.ts'>variables.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/comments/comments.ts'>comments.ts</a></td>
<td><b>92.86%</b></td>
<td><b>87.50%</b></td>
<td><b>98.23%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/comments/comments.ts#L44>44</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/comments/comments.ts#L45>45</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/comments/comments.ts#L61>61</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/comments/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/comments/components/annotation-filter.ts'>annotation-filter.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/comments/components/annotation-item.ts'>annotation-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/comments/components/annotation-pin.ts'>annotation-pin.ts</a></td>
<td><b>88.89%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/comments/components/annotation-pin.ts#L35>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/comments/components/annotation-resolved.ts'>annotation-resolved.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/comments/components/annotations.ts'>annotations.ts</a></td>
<td><span>100%</span></td>
<td><b>88.89%</b></td>
<td><b>90.10%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/comments/components/annotations.ts#L39>39</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/comments/components/annotations.ts#L40>40</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/comments/components/annotations.ts#L41>41</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/comments/components/annotations.ts#L42>42</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/comments/components/annotations.ts#L56>56</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/comments/components/annotations.ts#L57>57</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/comments/components/annotations.ts#L58>58</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/comments/components/annotations.ts#L74>74</a>, <a href=https://github.com/SuperViz/sdk/blob/7cb78fef0150a2dbe429e74c7adc7cf575a23b2b/src/web-components/comments/c [...]

2023-12-15 12:32 UTC, carlossantos74 requested changes

2023-12-15 12:32 UTC, carlossantos74 commented on src/services/realtime/ably/index.ts
> +
There you need to add a method to leave WIO channel

2023-12-15 13:36 UTC, SuperViz-Dev commented
Total Coverage: <b>98.04%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td colspan='5'><b>src/web-components</b></td></tr><tr><td colspan='5'><b>src/web-components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>80.52%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/base/index.ts#L29>29</a>, <a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/base/index.ts#L30>30</a>, <a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/base/index.ts#L43>43</a>, <a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/base/index.ts#L44>44</a>, <a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/base/index.ts#L45>45</a>, <a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/base/index.ts#L46>46</a>, <a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/base/index.ts#L47>47</a>, <a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/base/index.ts#L48>48</a>, <a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/base/index.ts#L49>49</a>, <a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/base/index.ts#L50>50</a>, <a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/base/index.ts#L51>51</a>, <a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/base/index.ts#L52>52</a>, <a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/base/index.ts#L53>53</a>, <a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/base/index.ts#L54>54</a>, <a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/base/index.ts#L55>55</a></td></tr><tr><td colspan='5'><b>src/web-components/base/styles</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/base/styles/icon-button.style.ts'>icon-button.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/base/styles/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/base/styles/sv-hr.style.ts'>sv-hr.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/base/styles/typography.style.ts'>typography.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/base/styles/variables.style.ts'>variables.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/comments/comments.ts'>comments.ts</a></td>
<td><b>92.86%</b></td>
<td><b>87.50%</b></td>
<td><b>98.23%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/comments/comments.ts#L44>44</a>, <a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/comments/comments.ts#L45>45</a>, <a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/comments/comments.ts#L61>61</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/comments/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/comments/components/annotation-filter.ts'>annotation-filter.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/comments/components/annotation-item.ts'>annotation-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/comments/components/annotation-pin.ts'>annotation-pin.ts</a></td>
<td><b>88.89%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/comments/components/annotation-pin.ts#L35>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/comments/components/annotation-resolved.ts'>annotation-resolved.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/comments/components/annotations.ts'>annotations.ts</a></td>
<td><span>100%</span></td>
<td><b>88.89%</b></td>
<td><b>90.10%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/comments/components/annotations.ts#L39>39</a>, <a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/comments/components/annotations.ts#L40>40</a>, <a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/comments/components/annotations.ts#L41>41</a>, <a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/comments/components/annotations.ts#L42>42</a>, <a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/comments/components/annotations.ts#L56>56</a>, <a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/comments/components/annotations.ts#L57>57</a>, <a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/comments/components/annotations.ts#L58>58</a>, <a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/comments/components/annotations.ts#L74>74</a>, <a href=https://github.com/SuperViz/sdk/blob/f521ba57b4badf3145f7302ad5cd0897ef8ed629/src/web-components/comments/c [...]

2023-12-15 13:40 UTC, SuperViz-Dev commented
Total Coverage: <b>91.92%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/shims.d.ts'>shims.d.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common</b></td></tr><tr><td colspan='5'><b>src/common/types</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/common/types/colors.types.ts'>colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/common/types/events.types.ts'>events.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/common/types/meeting-colors.types.ts'>meeting-colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/common/types/participant.types.ts'>participant.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/common/types/realtime.types.ts'>realtime.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/common/types/sdk-options.types.ts'>sdk-options.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common/utils</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/common/utils/do-request.ts'>do-request.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>87.50%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/common/utils/do-request.ts#L20>20</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/common/utils/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/common/utils/logger.ts'>logger.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/common/utils/observable.ts'>observable.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/common/utils/observer.ts'>observer.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/common/utils/sleep.ts'>sleep.ts</a></td>
<td><b>0%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/common/utils/sleep.ts#L2>2</a></td></tr><tr><td colspan='5'><b>src/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/components/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/components/comments/index.ts'>index.ts</a></td>
<td><b>92%</b></td>
<td><b>97.06%</b></td>
<td><b>98.48%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/components/comments/index.ts#L126>126</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/components/comments/index.ts#L193>193</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/components/comments/index.ts#L447>447</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/components/comments/index.ts#L544>544</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/components/comments/index.ts#L560>560</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/components/comments/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments/canvas-pin-adapter</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/components/comments/canvas-pin-adapter/index.ts'>index.ts</a></td>
<td><b>65.91%</b></td>
<td><b>96.55%</b></td>
<td><b>93.27%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/components/comments/canvas-pin-adapter/index.ts#L244>244</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/components/comments/canvas-pin-adapter/index.ts#L244>244</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/components/comments/canvas-pin-adapter/index.ts#L244>244</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/components/comments/canvas-pin-adapter/index.ts#L244>244</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/components/comments/canvas-pin-adapter/index.ts#L245>245</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/components/comments/canvas-pin-adapter/index.ts#L246>246</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/components/comments/canvas-pin-adapter/index.ts#L249>249</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/components/comments/canvas-pin-adapter/index.ts#L249>249</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/components/comments/canvas-pin-adapter/index.ts#L250>250</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/components/comments/canvas-pin-adapter/index.ts#L253>253</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/s [...]

2023-12-15 13:40 UTC, SuperViz-Dev commented
Total Coverage: <b>98.04%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td colspan='5'><b>src/web-components</b></td></tr><tr><td colspan='5'><b>src/web-components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>80.52%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/base/index.ts#L29>29</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/base/index.ts#L30>30</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/base/index.ts#L43>43</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/base/index.ts#L44>44</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/base/index.ts#L45>45</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/base/index.ts#L46>46</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/base/index.ts#L47>47</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/base/index.ts#L48>48</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/base/index.ts#L49>49</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/base/index.ts#L50>50</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/base/index.ts#L51>51</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/base/index.ts#L52>52</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/base/index.ts#L53>53</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/base/index.ts#L54>54</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/base/index.ts#L55>55</a></td></tr><tr><td colspan='5'><b>src/web-components/base/styles</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/base/styles/icon-button.style.ts'>icon-button.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/base/styles/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/base/styles/sv-hr.style.ts'>sv-hr.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/base/styles/typography.style.ts'>typography.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/base/styles/variables.style.ts'>variables.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/comments/comments.ts'>comments.ts</a></td>
<td><b>92.86%</b></td>
<td><b>87.50%</b></td>
<td><b>98.23%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/comments/comments.ts#L44>44</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/comments/comments.ts#L45>45</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/comments/comments.ts#L61>61</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/comments/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/comments/components/annotation-filter.ts'>annotation-filter.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/comments/components/annotation-item.ts'>annotation-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/comments/components/annotation-pin.ts'>annotation-pin.ts</a></td>
<td><b>88.89%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/comments/components/annotation-pin.ts#L35>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/comments/components/annotation-resolved.ts'>annotation-resolved.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/comments/components/annotations.ts'>annotations.ts</a></td>
<td><span>100%</span></td>
<td><b>88.89%</b></td>
<td><b>90.10%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/comments/components/annotations.ts#L39>39</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/comments/components/annotations.ts#L40>40</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/comments/components/annotations.ts#L41>41</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/comments/components/annotations.ts#L42>42</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/comments/components/annotations.ts#L56>56</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/comments/components/annotations.ts#L57>57</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/comments/components/annotations.ts#L58>58</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/comments/components/annotations.ts#L74>74</a>, <a href=https://github.com/SuperViz/sdk/blob/b66d666e2dbd4f4c1c4bf16b7070ef3637c58221/src/web-components/comments/c [...]

2023-12-15 14:10 UTC, SuperViz-Dev commented
Total Coverage: <b>91.89%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/shims.d.ts'>shims.d.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common</b></td></tr><tr><td colspan='5'><b>src/common/types</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/common/types/colors.types.ts'>colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/common/types/events.types.ts'>events.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/common/types/meeting-colors.types.ts'>meeting-colors.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/common/types/participant.types.ts'>participant.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/common/types/realtime.types.ts'>realtime.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/common/types/sdk-options.types.ts'>sdk-options.types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/common/utils</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/common/utils/do-request.ts'>do-request.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>87.50%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/common/utils/do-request.ts#L20>20</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/common/utils/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/common/utils/logger.ts'>logger.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/common/utils/observable.ts'>observable.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/common/utils/observer.ts'>observer.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/common/utils/sleep.ts'>sleep.ts</a></td>
<td><b>0%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/common/utils/sleep.ts#L2>2</a></td></tr><tr><td colspan='5'><b>src/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/components/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/components/comments/index.ts'>index.ts</a></td>
<td><b>92%</b></td>
<td><b>97.06%</b></td>
<td><b>98.48%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/components/comments/index.ts#L126>126</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/components/comments/index.ts#L193>193</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/components/comments/index.ts#L447>447</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/components/comments/index.ts#L544>544</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/components/comments/index.ts#L560>560</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/components/comments/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/components/comments/canvas-pin-adapter</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/components/comments/canvas-pin-adapter/index.ts'>index.ts</a></td>
<td><b>65.91%</b></td>
<td><b>96.55%</b></td>
<td><b>93.27%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/components/comments/canvas-pin-adapter/index.ts#L244>244</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/components/comments/canvas-pin-adapter/index.ts#L244>244</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/components/comments/canvas-pin-adapter/index.ts#L244>244</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/components/comments/canvas-pin-adapter/index.ts#L244>244</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/components/comments/canvas-pin-adapter/index.ts#L245>245</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/components/comments/canvas-pin-adapter/index.ts#L246>246</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/components/comments/canvas-pin-adapter/index.ts#L249>249</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/components/comments/canvas-pin-adapter/index.ts#L249>249</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/components/comments/canvas-pin-adapter/index.ts#L250>250</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/components/comments/canvas-pin-adapter/index.ts#L253>253</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/s [...]

2023-12-15 14:11 UTC, SuperViz-Dev commented
Total Coverage: <b>98.04%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td colspan='5'><b>src/web-components</b></td></tr><tr><td colspan='5'><b>src/web-components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>80.52%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/base/index.ts#L29>29</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/base/index.ts#L30>30</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/base/index.ts#L43>43</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/base/index.ts#L44>44</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/base/index.ts#L45>45</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/base/index.ts#L46>46</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/base/index.ts#L47>47</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/base/index.ts#L48>48</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/base/index.ts#L49>49</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/base/index.ts#L50>50</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/base/index.ts#L51>51</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/base/index.ts#L52>52</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/base/index.ts#L53>53</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/base/index.ts#L54>54</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/base/index.ts#L55>55</a></td></tr><tr><td colspan='5'><b>src/web-components/base/styles</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/base/styles/icon-button.style.ts'>icon-button.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/base/styles/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/base/styles/sv-hr.style.ts'>sv-hr.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/base/styles/typography.style.ts'>typography.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/base/styles/variables.style.ts'>variables.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/comments/comments.ts'>comments.ts</a></td>
<td><b>92.86%</b></td>
<td><b>87.50%</b></td>
<td><b>98.23%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/comments/comments.ts#L44>44</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/comments/comments.ts#L45>45</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/comments/comments.ts#L61>61</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/comments/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/comments/components/annotation-filter.ts'>annotation-filter.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/comments/components/annotation-item.ts'>annotation-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/comments/components/annotation-pin.ts'>annotation-pin.ts</a></td>
<td><b>88.89%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/comments/components/annotation-pin.ts#L35>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/comments/components/annotation-resolved.ts'>annotation-resolved.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/comments/components/annotations.ts'>annotations.ts</a></td>
<td><span>100%</span></td>
<td><b>88.89%</b></td>
<td><b>90.10%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/comments/components/annotations.ts#L39>39</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/comments/components/annotations.ts#L40>40</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/comments/components/annotations.ts#L41>41</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/comments/components/annotations.ts#L42>42</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/comments/components/annotations.ts#L56>56</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/comments/components/annotations.ts#L57>57</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/comments/components/annotations.ts#L58>58</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/comments/components/annotations.ts#L74>74</a>, <a href=https://github.com/SuperViz/sdk/blob/535cad58a8a62ae0b042173e5d9d45cf67ebc0ae/src/web-components/comments/c [...]

2023-12-15 16:23 UTC, merged

2023-12-18 11:12 UTC, SuperViz-Dev commented
:tada: This PR is included in version 5.3.0 :tada:

The release is available on:
- [GitHub release](https://github.com/SuperViz/sdk/releases/tag/v5.3.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@superviz/sdk/v/5.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-01-15 22:14 UTC, SuperViz-Dev commented
:tada: This PR is included in version 5.3.0-lab.1 :tada:

The release is available on:
- [GitHub release](https://github.com/SuperViz/sdk/releases/tag/v5.3.0-lab.1)
- [npm package (@lab dist-tag)](https://www.npmjs.com/package/@superviz/sdk/v/5.3.0-lab.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-01-19 16:58 UTC, SuperViz-Dev commented
:tada: This PR is included in version 5.3.0-beta.1 :tada:

The release is available on:
- [GitHub release](https://github.com/SuperViz/sdk/releases/tag/v5.3.0-beta.1)
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@superviz/sdk/v/5.3.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: